#!/usr/bin/env bash
# An Nginx server to listen on port 80 configuration:

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart

