#!/usr/bin/env bash
#   Creates /var/run/myscript.pid containing script PID as a file.
#   To infinity and beyond indefinitely is shown.
#   "I hate the kill command" upon receiving a SIGTERM shows.
#   "Y U no love me?!" upon receiving a SIGINT shows.
#   The file /var/run/mycript.pid and terminates upon is deleted.
#+  receiving a SIGQUIT or SIGTERM.

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
