#!/usr/bin/env bash

shows To infinity and beyond indefinitely file created by script.
#diplays I hate the kill command when receiving a SIGTERM signal.
#Deletes the file created and terminaes itself  when receiving a SIGQUIT or
#SIGTERM signal.

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
