#!/usr/bin/env bash
# Shows To infinity and beyond indefinitely.
# Sleep 2 in between each iteration added.
# I am invincible!!! when receiving a SIGTERM signal.

while true
do 
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
