#!/usr/bin/env bash
# Configures ubuntu server with the requirements as follows:
# 	     - localhost: Resolves -> 127.0.0.2
#	     - facebook.com: Resolves -> 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo -e "8.8.8.8\tfacebook.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
