#!/usr/bin/env bash
# File transferred from School's client to the other.
# Four arguments accepted:
#+    Path to file transferred.
#+    IP of the server to transfer file to.
#+    Username that scp connects with.
#+    Path to the SSH private key that utilized by scp.

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi

